import Head from 'next/head';
import Layout from 'components/layout';
import { MoneyList } from 'data/Data';
import MoneyCard from 'components/Home/2/MoneyCard';
import { useState } from 'react';
import { DownArrow } from 'components/icon';

export default function index() {
  const [isMoreView, setIsMoreView] = useState<Boolean>(false); // 더보기&접기 상태 저장
  const onClickMoreViewButton = () => {
    setIsMoreView(!isMoreView);
  }; // 클릭시 상태 반전

  // 더보기 버튼이 True일 때는 모두 보여주기
  // 더보기 버튼이 False일 때는 3개만 slice 해서 보여주기
  let SchoolMoney = isMoreView ? MoneyList : MoneyList.slice(0, 3);

  // 교내 장학
  const school = SchoolMoney?.map((el) => {
    return (
      <MoneyCard
        key={el.name}
        name={el.name}
        description={el.description}
        category={el.category}
        benefit={el.benefit}
      />
    );
  });
  // 교외 장학
  // const suburbs;
  console.log(isMoreView);
  return (
    <Layout>
      <Head>
        {/* 메타데이터 */}
        <title>장학금</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font ">
        <div className="container px-5 py-24 mx-auto flex-col flexBox">
          <div className="flex flex-wrap">{school}</div>
          <button className="flex-col flexBox" onClick={onClickMoreViewButton}>
            <p className="mb-4 font-base">더보기</p>
            <DownArrow />
          </button>
        </div>
      </section>
    </Layout>
  );
}
