import Head from 'next/head';
import Layout from 'components/layout';
import { MoneyList } from 'data/Data';
import MoneyCard from 'components/Home/2/MoneyCard';

export default function index() {
  return (
    <Layout>
      <Head>
        {/* 메타데이터 */}
        <title>장학금</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto flexBox">
          <div className="flex flex-wrap">
            {MoneyList?.map((el) => {
              return (
                <MoneyCard
                  key={el.name}
                  name={el.name}
                  description={el.description}
                  category={el.category}
                  benefit={el.benefit}
                />
              );
            })}
          </div>
        </div>
      </section>
    </Layout>
  );
}
