import Head from 'next/head';
import Layout from 'components/layout';
import { Check } from 'components/icon';

export default function index() {
  return (
    <Layout>
      <Head>
        {/* 메타데이터 */}
        <title>심리학과에서 메일 쓰기</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto flex flex-col">
          <h1 className="text-6xl sm:text-3xl font-bold font-sans text-gray-900 mb-4 text-left">
            심리학과 메일 쓰기
          </h1>
          <div className="w-full mx-auto flexBox flex-col">
            <h2 className="text-lg font-bold mb-16">공식적인 메일 작성 요소</h2>
            <div className="flex">
              {/* 제목 */}
              <div className="flex ">
                <div className="mr-2.5 w-12 h-12 flex-shrink-0 flexBox bg-primaryColor circle text-slate-50">
                  제목
                </div>
                <div>
                  <div className="flex ">
                    <Check /> <p className="ml-2">작성자의 소속</p>
                  </div>
                  <div className="flex mt-2.5">
                    <Check /> <p className="ml-2">메일의 목적</p>
                  </div>
                </div>
              </div>
              {/* 내용 */}
              <div className="flex ml-32">
                <div className="mr-2.5 w-12 h-12 flex-shrink-0 flexBox bg-[#505050] circle text-slate-50">
                  내용
                </div>
                <div>
                  <div className="flex ">
                    <Check /> <p className="ml-2">작성자 소개</p>
                  </div>
                  <div className="flex  mt-2.5">
                    <Check /> <p className="ml-2">메일의 목적</p>
                  </div>
                  <div className="flex  mt-2.5">
                    <Check /> <p className="ml-2">인사</p>
                  </div>
                  <div className="flex  mt-2.5">
                    <Check /> <p className="ml-2">보낸 이</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </Layout>
  );
}
