import Head from 'next/head';
import Layout from 'components/layout';
import { Enrolement, Study, Search } from 'data/Data';
import EnrolementCard from 'components/Home/6/EnrolementCard';

export default function index() {
  const Enrole = Enrolement?.map((el) => {
    return <EnrolementCard key={el.name} name={el.name} tip={el.tip} />;
  });

  const StudyTip = Study?.map((el) => {
    return <EnrolementCard key={el.name} name={el.name} tip={el.tip} />;
  });

  const SearchTip = Search?.map((el) => {
    return <EnrolementCard key={el.name} name={el.name} tip={el.tip} />;
  });
  return (
    <Layout>
      <Head>
        {/* 메타데이터 */}
        <title>심리학과에서 공부하기</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="text-gray-600 body-font bg-secondaryColor">
        <div className="container px-5 py-24 mx-auto flex-col flexBox ">
          <h1 className="text-6xl sm:text-3xl font-bold font-sans text-gray-900 mb-4 text-left">
            심리학과에서 공부하기
          </h1>
          <h1 className="text-xl font-semibold mb-8">
            수강신청 성공하는 꿀팁!🍯
          </h1>
          <div className="w-full h-96 flex flex-col flex-wrap items-center p-4 bg-fixed">
            {Enrole}
          </div>
        </div>
      </section>
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto flex-col flexBox ">
          <h1 className="text-xl font-semibold mb-8">학과 공부 꿀팁!🍯</h1>
          <div className="w-full h-96 flex flex-col flex-wrap items-center p-4 bg-fixed">
            {StudyTip}
          </div>
        </div>
      </section>
      <section className="text-gray-600 body-font bg-shadowColor">
        <div className="container px-5 py-24 mx-auto flex-col flexBox ">
          <h1 className="dark:text-slate-700 text-xl font-semibold mb-8">
            논문 검색 꿀팁!🍯
          </h1>
          <div className="w-full h-96 flex flex-col flex-wrap items-center p-4 bg-fixed">
            {SearchTip}
          </div>
        </div>
      </section>
    </Layout>
  );
}
