import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Layout from 'components/layout';
import { EnrolementProps } from 'shared/store/type';
import FreeCard from 'components/Graduate/FreeCard';

const FreePage = ({ Free }: any) => {
  const FreeList = Free.map((el: EnrolementProps, idx: number) => {
    return <FreeCard key={idx} idx={idx} name={el.name} tip={el.tip} />;
  });

  return (
    <Layout>
      <Head>
        {/* 메타데이터 */}
        <title>대학원 추천 커리큘럼</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-3 gap-4">{FreeList}</div>
    </Layout>
  );
};

export default FreePage;
