import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Layout from 'components/layout';
import { EnrolementProps } from 'shared/store/type';
import FreeCard from 'components/Graduate/FreeCard';
import GraduateHeader from 'components/Graduate/GraduateHeader';

const FreePage = ({ data }: any) => {
  const Free = data;
  const FreeList = Free.map((el: EnrolementProps, idx: number) => {
    return <FreeCard key={idx} idx={idx} name={el.name} tip={el.tip} />;
  });

  return (
    <Layout>
      <Head>
        {/* 메타데이터 */}
        <title>대학원 추천 커리큘럼</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <GraduateHeader />
          <div className="grid grid-cols-3 gap-4">{FreeList}</div>
        </div>
      </section>
    </Layout>
  );
};

export default FreePage;

import loadData from 'shared/utils/loadData';

export async function getStaticProps() {
  const data = await loadData({ subfolder: 'Graduate', file: 'Free' });

  return {
    props: {
      data,
    },
  };
}
