import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Layout from 'components/layout';
import { EnrolementProps } from 'shared/store/type';
import FreeCard from 'components/Graduate/FreeCard';
import GraduateHeader from 'components/Graduate/GraduateHeader';

const FreePage = ({ data }: any) => {
  const Free = data;
  const FreeList = Free.map((el: EnrolementProps, idx: number) => {
    return <FreeCard key={idx} idx={idx} name={el.name} tip={el.tip} />;
  });

  return (
    <Layout>
      <Head>
        {/* 메타데이터 */}
        <title>대학원 추천 커리큘럼</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="w-full h-32 bg-shadowColor rounded-lg flex mb-9 relative overflow-hidden">
            <div className="flex flex-col justify-center ml-8">
              <h1 className="text-xl font-bold mb-2 dark:text-slate-800">
                자유 발언
              </h1>
              <h2 className="text-base dark:text-slate-800">
                선배님들의 추가 조언을 전해드려요
              </h2>
            </div>
            {/* 반응형 위해 줄어들면 이미지는 없어지도록 */}
            <Image
              className="absolute -bottom-14 right-0 hidden lg:block"
              src="/images/대학원커리.webp"
              width={534}
              height={212}
              alt="대학원 커리큘럼 이미지"
              layout="full"
            />
          </div>
          <GraduateHeader />

          <div className="grid grid-cols-3 gap-4">{FreeList}</div>
        </div>
      </section>
    </Layout>
  );
};

export default FreePage;

import loadData from 'shared/utils/loadData';

export async function getStaticProps() {
  const data = await loadData({ subfolder: 'Graduate', file: 'Free' });

  return {
    props: {
      data,
    },
  };
}