import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import path from 'path';
import { promises as fs } from 'fs';
import Layout from 'components/layout';
import GraduateHeader from 'components/Graduate/GraduateHeader';

const Guide = () => {
  const PDFViewer = () => {
    return (
      <iframe src="/api/pdf" title="pdf-viewer" width="100%" height="768px" />
    );
  };
  return (
    <Layout>
      <Head>
        {/* 메타데이터 */}
        <title>대학원 입시요강</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="w-full h-32 bg-shadowColor rounded-lg flex mb-9 relative">
            <div className="flex flex-col justify-center ml-8">
              <h1 className="text-xl font-bold mb-2 dark:text-slate-800">
                대학원 입시요강
              </h1>
              <h2 className="text-base dark:text-slate-800">
                대학별 모집요강을 안내드려요
              </h2>
            </div>
            {/* 반응형 위해 줄어들면 이미지는 없어지도록 */}
            <Image
              className="absolute bottom-0 right-36 hidden lg:block"
              src="/images/대학원입시요강1.webp"
              width={242}
              height={186}
              alt="대학원 커리큘럼 이미지"
              layout="full"
            />
            <Image
              className="absolute -bottom-24 right-4 rotate-30 hidden lg:block"
              src="/images/대학원입시요강2.webp"
              width={242}
              height={186}
              alt="대학원 커리큘럼 이미지"
              layout="full"
            />
            <Image
              className="absolute -bottom-24 right-72 -rotate-45 hidden lg:block"
              src="/images/대학원입시요강2.webp"
              width={242}
              height={186}
              alt="대학원 커리큘럼 이미지"
              layout="full"
            />
          </div>
          <GraduateHeader />
          <PDFViewer />
        </div>
      </section>
    </Layout>
  );
};

export default Guide;

export async function getStaticProps() {
  // 커리큘럼
  const filePath = path.join(process.cwd(), 'data', 'GraduateCrc.json');
  const CurriData = await fs.readFile(filePath, 'utf8');
  const objectData = JSON.parse(CurriData);

  return {
    props: {
      CurriData: await Promise.all(objectData),
    },
  };
}
