import React, { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Layout from 'components/layout';
import GraduateHeader from 'components/Graduate/GraduateHeader';

const Guide = () => {
  const PDFViewer = () => {
    return (
      <iframe src="/api/pdf" title="pdf-viewer" width="100%" height="768px" />
    );
  };

  interface Tab {
    id?: string;
    label?: string;
    content?: React.ReactNode;
  }

  interface Props {
    tabs: Tab[];
  }

  const Tabs: React.FC<Props> = ({ tabs }) => {
    const [activeTab, setActiveTab] = useState(tabs[0].id);
    console.log(tabs);

    return (
      <>
        <ul className="flex flex-shrink-0 border-gray-200">
          {tabs.map((tab) => (
            <li
              key={tab.id}
              className={`m-4 w-56 h-12 p-4 flexBox text-base text-center cursor-pointer rounded-2xl border ${
                activeTab === tab.id ? 'bg-shadowColor' : ''
              }`}
              onClick={() => setActiveTab(tab.id)}
            >
              {tab.label}
            </li>
          ))}
        </ul>
        <div className="p-6">
          {tabs.find((tab) => tab.id === activeTab)?.content}
        </div>
      </>
    );
  };
  return (
    <Layout>
      <Head>
        {/* 메타데이터 */}
        <title>대학원 입시요강</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="w-full h-32 bg-shadowColor rounded-lg flex mb-9 relative">
            <div className="flex flex-col justify-center ml-8">
              <h1 className="text-xl font-bold mb-2 dark:text-slate-800">
                대학원 입시요강
              </h1>
              <h2 className="text-base dark:text-slate-800">
                대학별 모집요강을 안내드려요
              </h2>
            </div>
            {/* 반응형 위해 줄어들면 이미지는 없어지도록 */}
            <Image
              className="absolute bottom-0 right-36 hidden lg:block"
              src="/images/대학원입시요강1.webp"
              width={242}
              height={186}
              alt="대학원 커리큘럼 이미지"
              layout="full"
            />
            <Image
              className="absolute -bottom-24 right-4 rotate-30 hidden lg:block"
              src="/images/대학원입시요강2.webp"
              width={242}
              height={186}
              alt="대학원 커리큘럼 이미지"
              layout="full"
            />
            <Image
              className="absolute -bottom-24 right-72 -rotate-45 hidden lg:block"
              src="/images/대학원입시요강2.webp"
              width={242}
              height={186}
              alt="대학원 커리큘럼 이미지"
              layout="full"
            />
          </div>
          <GraduateHeader />
          <Tabs
            tabs={[
              { id: '1', label: '서울대학교 모집요강', content: <PDFViewer /> },
              { id: '2', label: '고려대학교 모집요강' },
              { id: '3', label: '연세대학교 모집요강' },
              { id: '4', label: '아주대학교 모집요강' },
            ]}
          />
        </div>
      </section>
    </Layout>
  );
};

export default Guide;
