import GraduateLife from 'data/GraduateLife.json';
import Layout from 'components/layout';
import Head from 'next/head';
import Image from 'next/image';
import GraduateHeader from 'components/Graduate/GraduateHeader';
import Life from 'components/Graduate/Life';
import { QnAProps } from 'shared/store/type';

export default function main() {
  console.log(GraduateLife);
  const GraduateLifeList: JSX.Element[] = GraduateLife.map((el: QnAProps) => (
    <Life key={el.id} question={el.question} answer={el.answer} />
  ));
  return (
    <Layout>
      <Head>
        {/* 메타데이터 */}
        <title>대학원 생활</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font  dark:bg-slate-800">
        <div className="container px-5 py-24 mx-auto flex-row flex-wrap flexBox w-full mb-20">
          <div className="w-full h-32 bg-shadowColor rounded-lg flex mb-9 relative overflow-hidden">
            <div className="flex flex-col justify-center ml-8">
              <h1 className="text-xl font-bold mb-2 dark:text-slate-800">
                대학원 생활
              </h1>
              <h2 className="text-base dark:text-slate-800">
                세부 전공 별 대학원 생활에 대한 정보를 알려드려요
              </h2>
            </div>
            {/* 반응형 위해 줄어들면 이미지는 없어지도록 */}
            <Image
              className="absolute -bottom-9 -right-14 hidden lg:block"
              src="/images/대학원생활.webp"
              width={641}
              height={270}
              alt="대학원 커리큘럼 이미지"
              layout="full"
            />
          </div>
          <GraduateHeader />
          {GraduateLifeList}
        </div>
      </section>
    </Layout>
  );
}
