import SurvivalWrapper from 'components/Home/SurvivalWrapper';
import { SurvivalProps } from 'shared/store/type';
import GraduateMain from 'data/GraduateMain.json';
import Layout from 'components/layout';
import Head from 'next/head';
import GraduateHeader from 'components/Graduate/GraduateHeader';

export default function main() {
  const GraduateTipList: JSX.Element[] = GraduateMain.map(
    (tip: SurvivalProps) => (
      <SurvivalWrapper
        key={tip.tipId}
        tipId={tip.tipId}
        title={tip.title!}
        subtitle={tip.subtitle!}
        category={tip.category!}
        homeImg={tip.homeImg!}
      />
    ),
  );
  return (
    <Layout>
      <Head>
        {/* 메타데이터 */}
        <title>대학원 추천 커리큘럼</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font bg-slate-200 dark:bg-slate-800">
        <div className="container px-5 py-24 mx-auto flex-row flex-wrap flexBox w-full mb-20">
          <GraduateHeader />
          {GraduateTipList}
        </div>
      </section>
    </Layout>
  );
}
