import Head from 'next/head';
import Layout from 'components/layout';
import Image from 'next/image';

export default function Home({ data }: any) {
  return (
    <>
      <Layout>
        <Head>
          {/* 메타데이터 */}
          <title>공군 장교</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <section className="text-gray-600 body-font">
          {/* 프로필 */}{' '}
          <div className="container px-5 py-24 mx-auto flexBox flex-col">
            <Image
              className="w-60 h-60 circle"
              src="/images/취업공군프로필.webp"
              width={250}
              height={250}
              alt="대학원 커리큘럼 이미지"
            />
          </div>
        </section>
      </Layout>
    </>
  );
}

import loadData from 'shared/utils/loadData';

export async function getStaticProps() {
  const data = await loadData({ subfolder: 'Career', file: 'Interview' });

  return {
    props: {
      data,
    },
  };
}
