import Head from 'next/head';
import Layout from 'components/layout';
import React from 'react';

import StatusChart from 'components/Career/StatusChart';
import FirstJobChart from 'components/Career/FirstJobChart';

export default function Home() {
  return (
    <>
      <Layout>
        <Head>
          {/* 메타데이터 */}
          <title>심리학과 취업정보</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <section className="text-gray-600 body-font ">
          <div className="container px-5 py-24 mx-auto flexBox flex-col">
            <StatusChart />
            <FirstJobChart />
          </div>
        </section>
      </Layout>
    </>
  );
}
