import Head from 'next/head';
import Image from 'next/image';
import { promises as fs } from 'fs';
import path from 'path';
import Layout from 'components/layout';

export default function Home({ HomeData }: any) {
  return (
    <>
      <Layout>
        <Head>
          {/* 메타데이터 */}
          <title>심리학과 취업</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <section className="text-gray-600 body-font bg-slate-200 dark:bg-slate-800 ">
          {/* 크롭해서 사용하기 때문에 화질 저하 문제 발생하는 것으로 보임. */}
          <Image
            src={'/images/취업.webp'}
            className="lg:h-48 md:h-36 w-full object-cover object-center mb-4"
            alt="picture"
            width={1920}
            height={200}
            priority={true}
          />
          <div className="container px-5 py-24 mx-auto ">
            <div className="flex-col flex-wrap flexBox w-full mb-20">
              <h1 className="text-4xl top-half">취업 현황</h1>
              {/* 취업 현황 배너 */}
              <div className="w-2/3 h-64 bg-gray-400 flex-col flex justify-end items-center p-8">
                <h1 className="text-2xl font-bold mb-2 text-slate-100">
                  취업 관련 정보
                </h1>
                <h2 className="text-base text-slate-100">
                  심리학과 취업률, 급여, 취직 분야 통계 자료
                </h2>
                <div className="w-40 h-9 border border-slate-100 flexBox">
                  <h2 className="px-5 text-xs text-slate-100">
                    취업 정보 바로가기
                  </h2>
                </div>
              </div>
              <div className="lg:w-1/2 w-full mb-6 lg:mb-0 ">
                <h1 className="text-left sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900 dark:text-gray-100">
                  Information
                </h1>
                <div className="h-1 w-20 my-2 mx-auto bg-indigo-500 rounded"></div>
              </div>
              <p className="text-center lg:w-1/2 w-full leading-relaxed text-gray-500">
                아주대학교 심리학과 학생들에게 유용한 정보를 소개합니다.
              </p>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  // 살아남기 데이터 경로
  const filePath = path.join(process.cwd(), 'data', 'HomeData.json');
  const HomeData = await fs.readFile(filePath, 'utf8');
  const objectData = JSON.parse(HomeData);

  return {
    props: {
      HomeData: await Promise.all(objectData),
    },
  };
}
