import path from 'path';
import { promises as fs } from 'fs';

import Head from 'next/head';
import Image from 'next/image';
import Layout from 'components/layout';

export default function graduate() {
  return (
    <Layout>
      <Head>
        {/* 메타데이터 */}
        <title>대학원</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Layout>
  );
}
