import Head from 'next/head';
import Layout from '../components/layout';

export default function Introduce() {
  return (
    <Layout>
      <Head>
        {/* 메타데이터 */}
        <title>구감단 소개</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>팀 소개</h1>
    </Layout>
  );
}
