import Head from 'next/head';
import Layout from 'components/layout';
import MajorRq from 'components/Tool/MajorRq';
import MajorCh from 'components/Tool/MajorCh';

export default function career() {
  return (
    <>
      {' '}
      <Layout>
        <Head>
          {/* 메타데이터 */}
          <title>도구</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className="text-gray-600 body-font">
          <div className="container px-5 py-12 mx-auto">
            <MajorRq />
            <MajorCh />
          </div>
        </section>
      </Layout>
    </>
  );
}
