name: Release Drafter
on:
  push:
    # main 브랜치에 푸쉬될 때 action 이 실행된다.
    branches:
      - main
jobs:
  update_release_draft:
    # 리눅스 환경에서 실행
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        # (Optional)
        # workflow 에서 여러 구성이 필요할 때 config-name 에 오버라이드 해줍니다.
        # 반드시 .github/ 에 위치해야합니다.
        with:
          config-name: release-drafter-config.yml
        env:
          # 토큰 필수!
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
            git config --global user.email "dhdms8696@naver.com"
            git config --global user.name "dorrion"
