# major, minor, patch 라벨에 따라 버전이 오른다.
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
# 설정된 레이블에 대한 타이틀로 분류함.
categories:
  - title: 'Features'
    label: 'enhancement'
    label: 'feature'
  - title: 'Fixes'
    label: 'fix'
    label: 'bug'
  - title: 'Etcetera'
    label: 'documentation'
# PR 내용이 릴리즈 노트에 보여질 형식 지정
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
# 어떤 버전을 증가시킬지 결정
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
# 릴리즈 노트의 형식
template: |
  ## 변경사항

  $CHANGES
